drm/msm/dpu: avoid open-coded 64-bit division
64-bit integer division is normally not allowed in the kernel
because of the large overhead on 32-bit machines:

drivers/gpu/drm/msm/disp/dpu1/dpu_core_perf.o: in function `_dpu_core_perf_crtc_update_bus':
dpu_core_perf.c:(.text+0x810): undefined reference to `__aeabi_uldivmod'

The function already contains a call to do_div(), so I assume this
is never called in a performance critical context, and we can
use div_u64 for the second one as well.

Fixes: 04d9044f6c57 ("drm/msm/dpu: add support for clk and bw scaling for display")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Georgi Djakov <georgi.djakov@linaro.org>
Signed-off-by: Rob Clark <robdclark@chromium.org>